---
title: "discussion"
author: "Grigor Dimitrov"
date: "September 23, 2016"
output: html_document
---

Behavioral data gives us an amazing capacity to understand the online behavior of the consumers as never before. Although the level of understanding of the consumers reached by the academia and practitioners is still great before the age of behavioral data, the capability of zooming into details of the real consumer behavior and the robustness of the insights are truly fascinating. Practically behavioral data empowers researchers to answer every question concerning the observable online behavior that comes to mind in a way beyond the capacity even of the consumer himself. Due to the complexity and fragmentation the consumer is unable to recall the information in such rich details as when it is recorded. 
Due to this fact the relationship under investigation have not been investigated before in such a detailed manner. This research confirms the finding from previous research in the area that the attitude towards uncertainty, but not risk is responsible for choosing a number of sources used for travel decision making. Our findings contribute to previous research through passive metering by investigating the time people spend on travel websites, as well as the efforts in terms of pageviews. The results from the analysis strongly confirm the hypotheses that both risk and uncertainty attitudes account for changes in time and pageviews spend desktop devices.

##Implications

##Contribution

This study contribute to 4 areas, it has been used as promotional material, methodologically to the area of behavioral research, to the stream of literature of decision making under risk and uncertainty, to tourism research and makes managerial implications for better online travel related marketing activities.

The findings serve as a tangible example of behavioral data employed in practice. The work been used as promotional marketing material to promote the business of Wakoopa. Insert blogs in the appendix in case blog changes address etc.
The main contribution of the research is adding methodologically to the emerging stream of research in the behavioral observational research. The research explores unobservable attitudes of one's personality assessed via questionnaires in relation to a real worlds observational data. Even though it uses an established and well known analysis techniques, the novelty in data collection techniques gives significant methodological contribution for practitioners and the academia.
The research contributes to the area of behavioral economics more precisely in decision under risk and uncertainty. It expands the area in relation to of online travel related behavior. It confirm the notion ones that attitude toward risk and uncertainty play a significant role in decision making concerning travel related information search and that individuals with plausible attitude toward both constructs spend less time in planning whereas those more concerned with the risk and uncertainty in general are more careful planners.

##Managerial implications

##Limitations & Recommendation

1. Risk and uncertainty measurement. The risk and uncertainty attitudes have been measured using the shorted possible way for measurement assessing only the general attitude of these personality traits. Arguably there could be discrepancies between the general attitude and domain specific attitude. Therefore, the experiment can be reproduced using more sophisticated measurement of risk and uncertainty attitudes such as gambles and lotteries as well as assessing perceived risks in travel related domains.

2. Classification. The classification used in the research has been used as it is provided, however it is possible to employ better classification algorithms providing better fragmentation of the travel related behavior. Therefore, for future research I suggest the use of better classification.
Micro-moment, the length of a micro-moment has been set to be 5 minutes without any reference or estimation whatsoever. There is a research that suggest how a best way cut off point in order to measure user sessions can be estimated. Furthermore, we use the same cut off point of 5 minutes across desktop and mobile device. As the activity over both type of devices largely differs it could be necessary to use different cut-off points per desktop and mobile. This would also mean that the comparison between desktop and mobile is harder as it is generally different.

3. Multiple users per device. It is known that some desktop devices are shared in the households, therefore we are recording data streams from different users  and assessing these data as coming from a single user. Thus, the analysis of this data can be biased as we 1) cannot distinguish the different users and 2) cannot connect properly the survey data with the behavioral data.

4. Time is inferred. The measurement cut off point is 2 seconds anything shorter than two seconds is not recorded. Crosstab browsing on desktop devices cannot be accessed. There is a measurement error on mobile devices which makes it possible to have events with time zero.

5. Selection bias. One should not overlook the possibility for selection bias as the people who agree to be tracked can be arguably different than the ones who are more privacy conscious and would not agree to share such information even for research purposes. Selection bias states that the selected sample who agrees to participate in the research may yield different characteristics than the sample of interest drawn from the general population.

6. Programming. The program written to process and analyze the data contains several thousand lines of code. Developing such a code in an absence of a quality assurance team and/or a proper quality assurance procedures is prompt to errors.

7. Measurement. income - time -




 


 


	





