---
title: "Literature review"
author: "Grigor Dimitrov"
date: "September 27, 2016"
output: word_document
---

In this chapter, I will review the main literature stream relevant for the hypnotized relationships in this paper. First, I will review online travel related activities and information search. Second, I will focus on risk and uncertainty attitudes and expand to risk and uncertainty attitudes related to travel and tourism. Third, I will briefly explore the big five inventory and its utilization in tourism research. In the final section of this chapter, I will derive the hypotheses of this research.

##Travel related activities and information search

Tourism related information search and planning has been a widely researched topic. Internet search behavior in tourism context has been examined primarily from the perspective of demographic variables, motivation and prior knowledge about the destination [@Jani2014]. In a paper exploring longitudinal data for 12 years, <!-- REF -->@Xiang2015 identified as a key trend number one that the internet penetration among consumers using the Internet for travel planning already reached the level of saturation. However, in a research exploring the online behavior from a generation perspective, <!-- REF -->@Kim2015 noted that there is no sufficient amount of research with regards to how the newly emerged segments of consumers behave online and use the internet for travel planning. 

@Xiang2015 turn special attention on travel planning process as a specific type of information search that is an important component of the decision making in tourism. During the planning, consumers obtain information based on which they choose their destinations and form their expectations. There is a substantial amount of research that looks at travel planning from different perspectives, some aim to identify the characteristics of the travelers' demographic characteristics (e.g. @kim2007gender), other investigate the way travelers are conducting purchases and navigate in the information stream (e.g. @Jun2007), and recently social media and its influence on travel have been in the focus of researchers as well (e.g. @xiang2010role).

From a practitioner standpoint, the more consumers are being active online the more prerequisites this creates for the tourism stakeholders marketeers to reach them during their decision-making process.  Therefore, identifying the travel planning process i.e. the decision-making journey is a critical step for the brands to intervene and influence the consumers in their direction <!-- REF -->[@googletravel2014]. Practitioners define that the decision-making process related to the tourism as an array of micro moments which often are not even conscious to the consumers. A micromoment is essentially a user session with the particular goal of obtaining information or committing to a purchase. 

For the purpose of this research, it is important to define the main components of the travel planning. In a meta-analysis, <!-- REF -->@Jun2007 point out that there is a consensus among researchers that travel planning cannot be simplified to a single goal-oriented rational action but it is rather viewed as a complex task involving multiple goals and decisions around the different goals and characteristics of the trip. The authors define a conceptual model for travel planning which has three main sequential interrelated components, pre-trip, during trip and post-trip. This research focuses on pre-trip phase. Pre-trip phase itself consists of information search and planning (decision making), furthermore, travel related purchases also occur at the end of this phase as well as during the trip itself.

<!-- REF -->@Jun2007 define travel plan as a complex decision involving an assessment of multiple alternatives organized around the travel goals in mind. The planning process includes setting goals and considering alternatives in order to achieve that goals including an evaluation of different alternatives' outcomes. Planning is dependent on the all information search behavior, utilization of the obtained information, purchase behavior and activities including past experience. <!-- REF -->@Pan2006 define vacation planning over the internet as an interaction between the user and the "online space" related to destinations and tourism. The online space contains content provided by diverse sources and the technology that facilitates the communication. User's "situation, knowledge and skills" combined with the "online space" contribute to the effective search.

It is important to be noted that trip planning is an important and enjoyable part of the vacation experience itself [@Stewart1999] and it is likely to be high costs and high involvement decision [@Bonn1998]. Furthermore, travel information search behavior explains travel purchase behavior [@woodside1994general]. <!-- REF -->@Quintal2010 review numerous aspect of from which information search has been researched including the amount of search, the number of sources, the search process, involvement, socio-demographic differences, culture etc.

<!-- REF -->@Pan2006 review the consumer vacation planning process from micro level perspective. Their research is motivated by the fact that previous research has been mostly focused on exploring planning and information search on macro level i.e. motivation, need, determinants, and outcomes. Their research focuses on a "snapshot" of travel planning where subjects make choices regarding a hypothetical holiday trip to San Diego. Using such setting it was possible to observe different chapters containing many episodes on how consumers adapt in their online search and come up with a final decision. These episodes or micromoments defined above represent one of the main variables of interest of this research.

Additionally, I will use the metrics defined by <!-- REF -->@Ho2005 in "An exploratory investigation of web-based tourist information search behavior". The researchers explored and characterized the online behavior of 96 subjects in laboratory research by assigning them one tourism related task and recording their desktop activity. <!-- REF -->@Ho2005 empirically analyzed the recorded videos and reported on different measures, representing the information search behavior. 

Additionally to micromoments, in this paper, I will adapt measures utilized in <!-- REF -->@Ho2005. The full list of dependent variables representing the internet search behavior includes:

* Total number of micromoments on travel related websites
* Total number of unique travel related domains (breadth of search)
* Total number of pageviews on travel related domains (depth of search)
* Total time spend on travel related domains
* Total sum of all travel related micromoments (this measure has been introduced due to one particular limitation of the mobile measurement discussed in the limitations section)

<!-- REF -->@Ho2005 conducted the research in laboratory environment exploring a single goal-directed session of activity. However, the whole information search planning and purchasing usually happen on many occasions within a longer period. Planning is fragmented on many episodes each characterized with its own purpose reflecting a specific problem [@Pan2006]. In this research, I will use real-life data representing the actual subjects' behavior. In this sense, the data is highly accurate and gives a detailed representation of the internet search behavior.

In conclusion, information search behavior is an important phase of the of the overall tourism behavior and more specifically the travel planning. From tourism stakeholders' perspective, it is a crucial phase where the consumer can be influenced by effective communication strategies and communication systems.

##Risk and uncertainty

Risk attitudes are a central part of the economic theory. Classical economic theory of decision under risk states that the risk is related to the probability of the occurrence of the specific outcome. For example, according to expected utility a prospect with probability P to win x amount of money opposed to 1-P to win nothing, will be evaluated as follows: p.u(x)+(1-p)u(0) where u is the utility function of money. Risk attitudes are defined as follows, risk aversion is an attitude which is manifested by the preference of the sure outcome over a prospect with higher expected value that involves risk. Whereas, risk seeking attitude will occur when the prospect is preferred over the sure amount.

Later economic theory evolves by distinguishing individual level probability weighing and utility weighting by taking into account different psychological variables. <!-- REF -->[@woodside1994general] propose "Prospect theory" to explain choices among risky prospects that are inconsistent with the standard economic theory. In these recent developments, the risk attitudes evolve. In order to explain decision making under risk scholars explore choices involving a different amount of risk (high risk and low risk) and associated with outcome involving different monetary values (again high and low) as well gains or loses.

In a paper focused on risk measurement in consumer research @Mandrik2005 summarize that the measurement of risk attitudes typically has been assessed in three ways. The first method involved "choice dilemmas" where subjects are presented with several scenarios and asked for their preference between two courses of action, this results in computing an overall score which is used to determine respondents' risk attitude. The second method involves gambles. Subjects are asked to choose an amount in order to participate in a gamble. Finally, researchers use self-reported measures. These include the creation of different scales that are measure risk and uncertainty in specific decision situations. The authors validate a novel self-reported scale which measures general risk attitude as a valid psychometrical measure. The construct proposed by @Mandrik2005 has been utilized in this research as it provides shorter and simple manner of assessing risk attitudes. 

##Risk and uncertainty in tourism
As noted above, one of the reasons researchers claims to cause the extensive information search is risk and uncertainty minimization. @Stewart1999 attribute uncertainty as an implicit and universal characteristic of every planning process. Furthermore, the authors argue that in order to handle uncertainty the travelers prepare more than one plan for their trips. @sweeney1999role point out that consumers who are more sensitive to risk and uncertainty engage in more extensive search in order to avoid them. @sirakaya2005building claim that because of the intangible nature of tourism products the uncertainty in tourism is higher than comparing to other products or services.

An important remark related to risk and uncertainty is the difference between both constructs. The difference between them lays in the probabilities of their outcomes, while risk is associated outcomes with known probabilities, uncertainty is associated with outcomes with unknown probabilities. @Quintal2010 investigate the difference between risk and uncertainty on a country level using @hofstede1980motivation uncertainty avoidance index (UAI) and risk scale measurement on tourists' information search. The researchers claim that many other papers do not make the distinction and this is especially problematic when researchers are using country UAI scores to explain individual-level behavior as individuals differ with regards to their attitudes of risk and uncertainty.

@Quintal2010 explain the relationship between uncertainty and risk in tourism and information search to be translated in the following way. In the early stages of their research, consumers search for information extensively and the outcomes are associated with uncertainty because the rate of occurrences of certain threatening events or undesirable outcomes is not known. In a later stage of the decision-making process, when travelers have already selected possible alternatives, the risk attitude is more likely to have an influence as consumers can assign relative probabilities to a few selected alternatives i.e. alternatives are being compared to one another providing a reference point.

Based on the relationship explained above, @Quintal2010 provide a hypothesis that the uncertainty attitude has an influence on the extent of the information search while holding risk attitude constant. With regards to the risk attitude, @Quintal2010 provide a hypothesis that risk attitude doesn't influence the extent of the information search, holding uncertainty attitude constant. This hypothesis, however, has been defended under the notion that all the information search has been performed during the early stage of the trip planning and in the later stage consumers only compare alternatives based on the information they gathered in the early stage. However, in a conceptual model of trip planning presented by @Jun2007, the information search is a component of all phases of the trip planning, including pre-trip, during trip and post-trip. Therefore, I find it credible to hypothesize that both risk and uncertainty attitudes influence the extent of the information search.

I further extend my hypotheses, regarding the direction of the effect. My hypotheses are based on @urbany1989buyer and @gemunden1985perceived claiming that information search is an instrument consumers use to minimize respectively the uncertainties and risks anticipated with regards to future purchases. For example, @gemunden1985perceived finds that when the complexity of the decision making is increasing, so does the information search. They attribute this to higher risks involved in that decisions. As travel planning is regarded as a complex task, I can expect the same relationship. @urbany1989buyer outlines two types of uncertainty, choice and knowledge uncertainty, choice uncertainty is related to uncertainties choosing a particular alternative amongst many, while knowledge uncertainty is related to familiarity with the product features. Their findings suggest that choice uncertainty has a positive relationship with the extent of the information search.

Based on the literature review above about information search, travel planning and risk and uncertainty hereby I form the following hypotheses:

*    H1. Risk seeking attitude decreases the extent of information search, keeping other factors constant.
*    H2. Uncertainty seeking attitude decreases the extent of information search, keeping other factors constant.


##Big Five Factors Inventory (BFI)

According to @leung2010review, the usage of personality traits in travel related literature appears to be low even though the academics agreed upon their value in Marketing domain [@baumgartner2002toward]. Personality is a temperament or person's inherent qualities of mind and strategies according to which one behaves, dispositions and behavioral patterns that are stable across time and can be used to characterize one's behavior. The trait perspective has been frequently utilized in consumer research because their ease of application as a self-reported measure and the measurement outputs can be easily applied in the statistical analysis. [@Jani2014].

Big five inventory (BFI) is the most well-known and established factor structure to measure personality [@denissen2008development]. It has been validated on many occasions and widely utilized by researchers, creating prerequisites to compare findings across different studies. Another important factor for the popularity of BFI is the fact they are freely available to use along with their validated translations in many languages. BFI has been proposed as a fundamental lexical hypothesis by Galton in 1884 [@goldberg1993structure], which is a language taxonomy of human temperament based on adjectives describing different personality traits. The theory was put into practice by @goldberg1993structure and it has been greatly developed ever since, leading to the construction of five broad factors. BFI are based on factor analysis where a large group of traits is shown to be correlated and grouped into five universal traits. 

BFI consists of Extraversion, Neuroticism, Conscientiousness, Agreeableness and Open to experience. Openness to experience is related to the degree of curiosity, inventiveness, adoption of novelty on the one hand and consistency and cautiousness on the other. That is, persons with high openness tend to be open-minded, adventurous while low openness can describe individuals that are more pragmatic. Conscientiousness reflects on the tendency for one to be organized, non-spontaneous, organized and efficient. Extroversion is related to traits such as outgoing personality, sociability, talkativeness. Personalities exhibiting low extroversion, on the other hand, can be perceived as less open and reserved. Agreeableness is described as a person being more compassionate and cooperative. It measures whether a person can be trusted or not and if they are well-tempered. High agreeableness personalities are seen as more naïve, while low are seen as more dominative and competitive. Finally, neuroticism explores the emotional stability of individuals. That is a high need for stability results in individuals who are clam and stable, while a low need for stability can describe emotionally unstable individuals.

These five factors are shown to be the main factors that drive human behavior, appear in different cultures, are relatively stable across the lifetime of subjects and have strong predictive validity [@Jani2014]. Researchers using BFI often aim to measure big five personality dimensions using as less as possible items which lead to the development and validation of short scales of BFI [[@denissen2008development].

## Personality traits and tourism information search

In tourism domain, BFI has been examined with regards to general travel behavior, the undertaken activities in the travel destination, adventure tourism and pilgrim tourism [@Jani2014]. There are two articles researching internet search behavior from the perspective of BFI. @Jani2011 proposes a model relating information needs and tourist information behavior from the perspective of BFI and travel personality. It defines tourists' information needs as reasons for collecting information. Information search behavior is defined as breadth and depth of information sources that consumers use to obtain information. Furthermore, @Jani2014, research the relationship between BFI and internet search behavior. Using self-reported survey data, they observe that travel related information sought online varies with regards to the different personalities. The authors conclude that some of the factors from the BFI can improve the information search behavior predictability.

@Jani2014 address the research question whether BFI can be used as a predictor of internet search behavior in terms of sources of information and the extent of the information sought. Using self-reported measures for internet information search and channels used, the authors confirm that personality traits can be used as a predictor of information search behavior.

As BFI in tourism has not been researched thoroughly, in this research I will commit to hypotheses concerning the relationship between personality traits and information search behavior. However, the BFI will be used in the research design and analysis of this paper along with trip characteristics as control variables. 




## Hypotheses

Based on the literature review, here I define the full list of hypotheses relating each of them to the main variables of interest in regards to travel related activities as listed above. The following relationships between observed behavior and unobservable personality traits are researched: 


|    |Hypotheses             ||||
|----|----------------------:|:-----------:|----:|:--------------|
| H1 | Risk attitude        | *Decreases* the amount of | a. | Micromoments |
|    |                      |           | b. | Domains      |
|    |                      |           | c. | Pageviews    |
|    |                      |           | d. | Time         |
|    |                      |           | e. | Lenght       |
| H2 | Uncertainty attitude | *Decreases* the amount of | a. | Micromoments |
|    |                      |           | b. | Domains      |
|    |                      |           | c. | Pageviews    |
|    |                      |           | d. | Time         |
|    |                      |           | e. | Length       |

As mentioned above I will run an exploratory analysis of the impact of the big five personality traits on online travel behavior. However, I will not commit to a hypothesis with regards to their effect or direction.
