

rawsurvey <- export_files$full_info_sdata[55:105]


fcols <- c("S1","S2","S3","S4",
           "D2","D3",
           "Q1","Q1b","Q2",
           "Q5A",
           "Q6.1","Q6.2","Q6.3",
           "Q8")

fcolsyn <- c("Q5_1","Q5_2","Q5_3","Q5_4","Q5_5","Q5_6",  
             "Q11_1","Q11_2","Q11_3","Q11_4","Q11_5")

fcolsad <- c("Q15_1","Q15_2","Q15_3","Q15_4","Q15_5","Q15_6","Q15_7","Q15_8","Q15_9","Q15_10","Q15_11",
             "Q16_1","Q16_2","Q16_3","Q16_4","Q16_5","Q16_6","Q16_7")

numericcols <- c("D1","Q4","Q7","Q9","Q10","Q18.1.value")

rawsurvey$D1 <- as.integer(rawsurvey$D1)
rawsurvey$Q4 <- as.integer(rawsurvey$Q4)
rawsurvey$Q7 <- as.integer(rawsurvey$Q7)
rawsurvey$Q9 <- as.integer(rawsurvey$Q9)
rawsurvey$Q10 <- as.integer(rawsurvey$Q10)
rawsurvey$Q18.1.value <- as.integer(rawsurvey$Q18.1.value)



rawsurvey[fcolsyn] <- lapply(rawsurvey[fcolsyn], factor, 
                             levels=c(1,2), 
                             labels = c("YES", "NO"),
                             exclude = NA
)

rawsurvey[fcolsad] <- lapply(rawsurvey[fcolsad], factor, 
                             levels=c(1:5), 
                             labels = c("SD", "D", "NAND","A","SA"),
                             exclude = NA
)



rawsurvey$S1 <- as.factor(rawsurvey$S1)
rawsurvey$S1 <- factor(rawsurvey$S1, 
                       levels = c("1","2","3","4"),
                       labels = c("No trips","One Trip","Two trips","Three+"),
                       exclude = NA
)
rawsurvey$S2 <- as.factor(rawsurvey$S2)
rawsurvey$S2 <- factor(rawsurvey$S2, 
                       levels = c("1","2","4"),
                       labels = c("Flight","Accomodation","None"),
                       exclude = NA
)
rawsurvey$S3 <- as.factor(rawsurvey$S3)
rawsurvey$S3 <- factor(rawsurvey$S3, 
                       levels = c("1","2","3"),
                       labels = c("Main Decision","Part Decision","Not part of decision"),
                       exclude = NA
)
rawsurvey$S4 <- as.factor(rawsurvey$S4)
rawsurvey$S4 <- factor(rawsurvey$S4, 
                       levels = c("1","2","3"),
                       labels = c("Leasure","Business","Leasure and Business"),
                       exclude = NA
)


rawsurvey$D2 <- as.factor(rawsurvey$D2)
rawsurvey$D2 <- factor(rawsurvey$D2, 
                       levels = c("1","2"),
                       labels = c("Man","Woman"),
                       exclude = NA
)
rawsurvey$D3 <- as.factor(rawsurvey$D3)
rawsurvey$D3 <- factor(rawsurvey$D3, 
                       levels = c(1:8),
                       labels = c("Minimum (minder dan € 12.500)","Beneden modaal (€ 12.500 - < € 26.500)","Bijna modaal (€ 26.500 - < € 33.000)","Modaal (€ 33.000 - < € 39.500)","Tussen 1 en 2 keer modaal (€ 39.500 - < € 66.000)","Twee keer modaal (€ 66.000 - < € 78.500)","Meer dan twee keer modaal (€ 78.500 of meer)","Onbekend"),
                       exclude = NA
)
rawsurvey$Q1<- as.factor(rawsurvey$Q1)
rawsurvey$Q1 <- factor(rawsurvey$Q1, 
                       levels = c(1:6),
                       labels = c(
                         "Europe",
                         "Asia",
                         "North America",
                         "South America",
                         "Australia",
                         "Africa"),
                       exclude = NA
)

countries <- c("Afrika",
               "Algerije",
               "Angola",
               "Benin",
               "Botswana",
               "Burkina Faso",
               "Burundi",
               "Centraal-Afrikaanse Republiek",
               "Comoren",
               "Congo",
               "Congo-Kinshasa",
               "Djibouti",
               "Egypte",
               "Equatoriaal-Guinea",
               "Eritrea",
               "Ethiopië",
               "Gabon",
               "Gambia",
               "Ghana",
               "Guinee",
               "Guinee-Bissau",
               "Ivoorkust",
               "Kaapverdië",
               "Kameroen",
               "Kenia",
               "Lesotho",
               "Liberia",
               "Libië",
               "Madagaskar",
               "Malawi",
               "Mali",
               "Marokko",
               "Mauritanië",
               "Mauritius",
               "Mayotte",
               "Mozambique",
               "Namibië",
               "Niger",
               "Nigeria",
               "Oeganda",
               "Rwanda",
               "Réunion",
               "Sao Tomé en Principe",
               "Senegal",
               "Seychellen",
               "Sierra Leone",
               "Sint-Helena",
               "Soedan",
               "Somalië",
               "Swaziland",
               "Tanzania",
               "Togo",
               "Tsjaad",
               "Tunesië",
               "Westelijke Sahara",
               "Zambia",
               "Zimbabwe",
               "Zuid-Afrika",
               "Amerika",
               "Amerikaanse Maagdeneilanden",
               "Anguilla",
               "Antigua en Barbuda",
               "Argentinië",
               "Aruba",
               "Bahama’s",
               "Barbados",
               "Belize",
               "Bermuda",
               "Bolivia",
               "Brazilië",
               "Britse Maagdeneilanden",
               "Canada",
               "Caymaneilanden",
               "Chili",
               "Colombia",
               "Costa Rica",
               "Cuba",
               "Dominica",
               "Dominicaanse Republiek",
               "Ecuador",
               "El Salvador",
               "Falklandeilanden",
               "Frans-Guyana",
               "Grenada",
               "Groenland",
               "Guadeloupe",
               "Guatemala",
               "Guyana",
               "Haïti",
               "Honduras",
               "Jamaica",
               "Martinique",
               "Mexico",
               "Montserrat",
               "Nederlandse Antillen",
               "Nicaragua",
               "Panama",
               "Paraguay",
               "Peru",
               "Puerto Rico",
               "Saint Barthélemy",
               "Saint Kitts en Nevis",
               "Saint Lucia",
               "Saint Pierre en Miquelon",
               "Saint Vincent en de Grenadines",
               "Sint-Maarten",
               "Suriname",
               "Trinidad en Tobago",
               "Turks- en Caicoseilanden",
               "Uruguay",
               "Venezuela",
               "Verenigde Staten",
               "Azië",
               "Afghanistan",
               "Armenië",
               "Azerbeidzjan",
               "Bahrein",
               "Bangladesh",
               "Bhutan",
               "Brunei",
               "Cambodja",
               "China",
               "Cyprus",
               "Filipijnen",
               "Georgië",
               "Hongkong SAR van China",
               "India",
               "Indonesië",
               "Irak",
               "Iran",
               "Israël",
               "Japan",
               "Jemen",
               "Jordanië",
               "Kazachstan",
               "Kirgizië",
               "Koeweit",
               "Laos",
               "Libanon",
               "Macao SAR van China",
               "Maldiven",
               "Maleisië",
               "Mongolië",
               "Myanmar",
               "Nepal",
               "Noord-Korea",
               "Oezbekistan",
               "Oman",
               "Oost-Timor",
               "Pakistan",
               "Palestijns Gebied",
               "Qatar",
               "Saoedi-Arabië",
               "Singapore",
               "Sri Lanka",
               "Syrië",
               "Tadzjikistan",
               "Taiwan",
               "Thailand",
               "Turkije",
               "Turkmenistan",
               "Verenigde Arabische Emiraten",
               "Vietnam",
               "Zuid-Korea",
               "Oceanië",
               "Amerikaans Samoa",
               "Amerikaanse kleinere afgelegen eilanden",
               "Antarctica",
               "Australië",
               "Bouveteiland",
               "Britse Gebieden in de Indische Oceaan",
               "Christmaseiland",
               "Cocoseilanden",
               "Cookeilanden",
               "Fiji",
               "Frans-Polynesië",
               "Franse Gebieden in de zuidelijke Indische Oceaan",
               "Guam",
               "Heard- en McDonaldeilanden",
               "Kiribati",
               "Marshalleilanden",
               "Micronesië",
               "Nauru",
               "Nieuw-Caledonië",
               "Nieuw-Zeeland",
               "Niue",
               "Noordelijke Marianeneilanden",
               "Norfolkeiland",
               "Palau",
               "Papoea-Nieuw-Guinea",
               "Pitcairn",
               "Salomonseilanden",
               "Samoa",
               "Tokelau",
               "Tonga",
               "Tuvalu",
               "Vanuatu",
               "Wallis en Futuna",
               "Zuid-Georgië en Zuidelijke Sandwicheilanden",
               "Europa",
               "Alandeilanden",
               "Albanië",
               "Andorra",
               "België",
               "Bosnië en Herzegovina",
               "Bulgarije",
               "Cyprus",
               "Denemarken",
               "Duitsland",
               "Estland",
               "Faeröer",
               "Finland",
               "Frankrijk",
               "Gibraltar",
               "Griekenland",
               "Guernsey",
               "Hongarije",
               "IJsland",
               "Ierland",
               "Isle of Man",
               "Italië",
               "Jersey",
               "Kroatië",
               "Letland",
               "Liechtenstein",
               "Litouwen",
               "Luxemburg",
               "Macedonië",
               "Malta",
               "Moldavië",
               "Monaco",
               "Montenegro",
               "Nederland",
               "Noorwegen",
               "Oekraïne",
               "Oostenrijk",
               "Polen",
               "Portugal",
               "Roemenië",
               "Rusland",
               "San Marino",
               "Servië",
               "Servië en Montenegro",
               "Slovenië",
               "Slowakije",
               "Spanje",
               "Svalbard en Jan Mayen",
               "Tsjechië",
               "Vaticaanstad",
               "Verenigd Koninkrijk",
               "Wit-Rusland",
               "Zweden",
               "Zwitserland")

rawsurvey$Q1b<- as.factor(rawsurvey$Q1b)
rawsurvey$Q1b <- factor(rawsurvey$Q1b, 
                        levels = c(1:253),
                        labels = countries,
                        exclude = NA
)

rawsurvey$Q2<- as.factor(rawsurvey$Q2)
rawsurvey$Q2 <- factor(rawsurvey$Q2, 
                       levels = c(1:18),
                       labels = c(
                         "vóór week 9",
                         "Week 09, van: February 29, 2016, naar: March 6, 2016", 
                         "Week 10, van: March 7, 2016, naar: March 13, 2016", 
                         "Week 11, van: March 14, 2016, naar: March 20, 2016", 
                         "Week 12, van: March 21, 2016, naar: March 27, 2016", 
                         "Week 13, van: March 28, 2016, naar: April 3, 2016", 
                         "Week 14, van: April 4, 2016, naar: April 10, 2016", 
                         "Week 15, van: April 11, 2016, naar:April 17, 2016", 
                         "Week 16, van: April 18, 2016, naar: April 24, 2016", 
                         "Week 17, van: April 25, 2016, naar: May 1, 2016", 
                         "Week 18, van: May 2, 2016, naar: May 8, 2016", 
                         "Week 19, van: May 9, 2016, naar: May 15, 2016", 
                         "Week 20, van: May 16, 2016, naar: May 22, 2016", 
                         "Week 21, van: May 23, 2016, naar: May 29, 2016", 
                         "Week 22, van: May 30, 2016, naar: June 5, 2016", 
                         "Week 23, van: June 6, 2016, naar: June 12, 2016", 
                         "Week 24, van: June 13, 2016, naar: June 19, 2016", 
                         "na Week 24"),
                       exclude = NA
)


